{
  "name": "release",
  "on": {
    "push": {
      "tags": [
        "v*.*.*"
      ]
    }
  },
  "jobs": {
    "release": {
      "name": "Create GitHub Release",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2.3.4",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "Setup | go",
          "uses": "actions/setup-go@v2",
          "with": {
            "go-version": "^1.17.0"
          }
        },
        {
          "name": "Setup | Release notes",
          "run": "GO111MODULE=on go install github.com/git-chglog/git-chglog/cmd/git-chglog@0.9.1\ngit-chglog -c .github/chglog/release.yml $(git describe --tags) > RELEASE.md\n"
        },
        {
          "name": "Setup | Archive Module",
          "run": "7z a rust-docs.zip './src/*'"
        },
        {
          "name": "Deploy | Release",
          "uses": "softprops/action-gh-release@v1",
          "with": {
            "files": "rust-docs.zip",
            "body_path": "RELEASE.md"
          }
        }
      ]
    }
  }
}
